# Generated by Django 3.1.2 on 2020-11-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DEPENDENT',
            fields=[
                ('Name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='PATIENT_DETAILS',
            fields=[
                ('P_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=6)),
                ('City', models.CharField(default='Null', max_length=20)),
                ('Street', models.CharField(default='Null', max_length=20)),
                ('Pincode', models.IntegerField(default=0)),
                ('Symptomatic', models.BooleanField(default=False)),
                ('Previous_Disease', models.CharField(default='Null', max_length=20)),
                ('Still_Exists', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddConstraint(
            model_name='patient_details',
            constraint=models.CheckConstraint(check=models.Q(Age__gte=1), name='Pat_Age_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='patient_details',
            constraint=models.CheckConstraint(check=models.Q(Age__lte=120), name='Pat_Age_lte_120'),
        ),
        migrations.AddConstraint(
            model_name='dependent',
            constraint=models.CheckConstraint(check=models.Q(Age__gte=1), name='Dep_Age_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='dependent',
            constraint=models.CheckConstraint(check=models.Q(Age__lte=120), name='Dep_Age_lte_120'),
        ),
    ]
