# Generated by Django 3.1.2 on 2020-11-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WARD_DETAILS',
            fields=[
                ('Ward_No', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Capacity', models.IntegerField()),
            ],
        ),
    ]
